-- Matches the live Supabase project. Safe to re-run in the SQL Editor.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  category text,
  arabic text,
  english text,
  price text,
  image text
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text,
  customer_phone text,
  address text,
  map_url text,
  notes text,
  items jsonb default '[]'::jsonb,
  total bigint default 0,
  status text default 'new'
);

-- Only accounts listed here can see orders and edit the menu.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;

drop policy if exists "Admins can see own row" on public.admin_users;
create policy "Admins can see own row" on public.admin_users
for select to authenticated using (user_id = (select auth.uid()));

create or replace function public.is_admin()
returns boolean language sql stable security invoker set search_path = public
as $$ select exists (select 1 from public.admin_users where user_id = (select auth.uid())); $$;

-- orders: customers can only create new orders; only admins read/update them.
alter table public.orders enable row level security;
drop policy if exists "Anyone can create orders" on public.orders;
drop policy if exists "Authenticated users can update orders" on public.orders;
drop policy if exists "Authenticated users can view orders" on public.orders;
drop policy if exists "Public can create orders" on public.orders;
drop policy if exists "Admins can read orders" on public.orders;
drop policy if exists "Admins can update orders" on public.orders;

create policy "Public can create orders" on public.orders
for insert to anon, authenticated with check (status = 'new');
create policy "Admins can read orders" on public.orders
for select to authenticated using (public.is_admin());
create policy "Admins can update orders" on public.orders
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- menu_items: everyone can read, only admins add/edit/delete.
alter table public.menu_items enable row level security;
drop policy if exists "nine cafe policy" on public.menu_items;
create policy "nine cafe policy" on public.menu_items
for select to public using (true);
drop policy if exists "Admins can manage menu" on public.menu_items;
create policy "Admins can manage menu" on public.menu_items
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- To add another admin, create the account under Authentication > Users, then:
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'someone@example.com'
-- on conflict do nothing;
