-- Matches the live Supabase project. Safe to re-run in the SQL Editor.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  category text,
  arabic text,
  english text,
  price text,
  image text
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text,
  customer_phone text,
  address text,
  map_url text,
  notes text,
  items jsonb default '[]'::jsonb,
  total bigint default 0,
  status text default 'new'
);

-- Only accounts listed here can see orders and edit the menu.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;

drop policy if exists "Admins can see own row" on public.admin_users;
create policy "Admins can see own row" on public.admin_users
for select to authenticated using (user_id = (select auth.uid()));

create or replace function public.is_admin()
returns boolean language sql stable security invoker set search_path = public
as $$ select exists (select 1 from public.admin_users where user_id = (select auth.uid())); $$;

-- orders: customers can only create new orders; only admins read/update them.
alter table public.orders enable row level security;
drop policy if exists "Anyone can create orders" on public.orders;
drop policy if exists "Authenticated users can update orders" on public.orders;
drop policy if exists "Authenticated users can view orders" on public.orders;
drop policy if exists "Public can create orders" on public.orders;
drop policy if exists "Admins can read orders" on public.orders;
drop policy if exists "Admins can update orders" on public.orders;

-- (insert policy is defined below, after the table-ordering columns exist)
create policy "Admins can read orders" on public.orders
for select to authenticated using (public.is_admin());
create policy "Admins can update orders" on public.orders
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- menu_items: everyone can read, only admins add/edit/delete.
alter table public.menu_items enable row level security;
drop policy if exists "nine cafe policy" on public.menu_items;
create policy "nine cafe policy" on public.menu_items
for select to public using (true);
drop policy if exists "Admins can manage menu" on public.menu_items;
create policy "Admins can manage menu" on public.menu_items
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Live updates for the admin page (new-order alerts). RLS still applies.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders') then
    alter publication supabase_realtime add table public.orders;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Ordering from tables inside the cafe (QR code on each table)
-- ---------------------------------------------------------------------------
-- Each table has a secret code (token) that goes in its QR link: /?t=<token>.
-- Codes are generated by the database; read them in Table Editor > cafe_tables.
create table if not exists public.cafe_tables (
  number int primary key check (number > 0),
  token text not null unique default encode(extensions.gen_random_bytes(5), 'hex'),
  pos_x numeric not null default 50,   -- position on the admin floor plan, % from the left
  pos_y numeric not null default 50,   -- % from the top
  created_at timestamptz not null default now()
);
alter table public.cafe_tables enable row level security;

drop policy if exists "Admins manage tables" on public.cafe_tables;
create policy "Admins manage tables" on public.cafe_tables
for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.cafe_tables (number, pos_x, pos_y)
select n, 14 + ((n - 1) % 4) * 24, case when n <= 4 then 28 else 72 end
from generate_series(1, 8) as n
on conflict (number) do nothing;

alter table public.orders add column if not exists order_type text not null default 'delivery';
alter table public.orders add column if not exists table_number int references public.cafe_tables(number);
alter table public.orders drop constraint if exists orders_order_type_check;
alter table public.orders add constraint orders_order_type_check check (order_type in ('delivery', 'table'));

-- Direct inserts from the website can only be delivery orders;
-- table orders go through place_table_order().
drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders" on public.orders
for insert to anon, authenticated
with check (status = 'new' and order_type = 'delivery' and table_number is null);

create or replace function public.table_for_token(p_token text)
returns int
language sql stable security definer set search_path = public
as $$ select number from public.cafe_tables where token = p_token; $$;

-- Prices and item names come from menu_items, never from the browser.
create or replace function public.place_table_order(p_token text, p_items jsonb, p_notes text default null)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_table int;
  v_items jsonb;
  v_total bigint;
  v_id bigint;
begin
  select number into v_table from public.cafe_tables where token = p_token;
  if v_table is null then
    raise exception 'invalid table code';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then
    raise exception 'cart is empty or too large';
  end if;

  select
    jsonb_agg(jsonb_build_object(
      'id', m.id::text,
      'name', m.arabic,
      'quantity', q.qty,
      'unit_price', regexp_replace(m.price, '[^0-9]', '', 'g')::bigint,
      'subtotal', regexp_replace(m.price, '[^0-9]', '', 'g')::bigint * q.qty
    )),
    sum(regexp_replace(m.price, '[^0-9]', '', 'g')::bigint * q.qty)
  into v_items, v_total
  from (
    select (e->>'id')::bigint as id, least(greatest((e->>'quantity')::int, 1), 50) as qty
    from jsonb_array_elements(p_items) e
  ) q
  join public.menu_items m on m.id = q.id;

  if v_items is null then
    raise exception 'no valid menu items';
  end if;

  insert into public.orders (order_type, table_number, customer_name, customer_phone, address, map_url, notes, items, total, status)
  values ('table', v_table, 'طاولة ' || v_table, null, 'داخل الكافيه — طاولة ' || v_table, null,
          nullif(left(trim(coalesce(p_notes, '')), 500), ''), v_items, v_total, 'new')
  returning id into v_id;

  return jsonb_build_object('order_id', v_id, 'table', v_table, 'total', v_total);
end;
$$;

revoke all on function public.table_for_token(text) from public;
revoke all on function public.place_table_order(text, jsonb, text) from public;
grant execute on function public.table_for_token(text) to anon, authenticated;
grant execute on function public.place_table_order(text, jsonb, text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Staff roles: manager (everything) and cashier (orders + read-only menu)
-- ---------------------------------------------------------------------------
alter table public.admin_users add column if not exists role text not null default 'manager';
alter table public.admin_users drop constraint if exists admin_users_role_check;
alter table public.admin_users add constraint admin_users_role_check check (role in ('manager', 'cashier'));

-- is_admin() = any staff member (reads/updates orders); is_manager() = managers only
create or replace function public.is_manager()
returns boolean language sql stable security invoker set search_path = public
as $$ select exists (select 1 from public.admin_users where user_id = (select auth.uid()) and role = 'manager'); $$;

drop policy if exists "Admins can manage menu" on public.menu_items;
drop policy if exists "Managers can manage menu" on public.menu_items;
create policy "Managers can manage menu" on public.menu_items
for all to authenticated using (public.is_manager()) with check (public.is_manager());

drop policy if exists "Admins manage tables" on public.cafe_tables;
drop policy if exists "Managers manage tables" on public.cafe_tables;
drop policy if exists "Staff read tables" on public.cafe_tables;
create policy "Managers manage tables" on public.cafe_tables
for all to authenticated using (public.is_manager()) with check (public.is_manager());
create policy "Staff read tables" on public.cafe_tables
for select to authenticated using (public.is_admin());

-- The secret QR codes (token) are never readable from the website
revoke select, insert, update, delete on public.cafe_tables from anon, authenticated;
grant select (number, pos_x, pos_y, created_at) on public.cafe_tables to authenticated;
grant update (pos_x, pos_y) on public.cafe_tables to authenticated;

-- To add a staff member, create the account under Authentication > Users, then:
-- insert into public.admin_users (user_id, role)
-- select id, 'cashier' from auth.users where email = 'someone@example.com'   -- or 'manager'
-- on conflict (user_id) do update set role = excluded.role;
